name: application_library
description: "LibrerÃ­a: El Estudiante"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.2
  http: ^1.1.2
  intl: ^0.18.1
<<<<<<< HEAD
  provider: ^6.1.2
=======
>>>>>>> 59d6b5f641ef69c037a952d57e694c74cd42942a

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.1.0
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.13.1
<<<<<<< HEAD
  shared_preferences: ^2.2.2
=======
>>>>>>> 59d6b5f641ef69c037a952d57e694c74cd42942a

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
<<<<<<< HEAD
  image_path: "assets/fonts/icono de libreria.png"
=======
  image_path: "assets/fonts/Logo de la libreria el estudiante.png"
>>>>>>> 59d6b5f641ef69c037a952d57e694c74cd42942a
